name = "trojan-worker-custom"
type = "javascript"
account_id = "9db606e4da7ddb225e7fc6f34cf7357e"
workers_dev = true
compatibility_date = "2022-05-03"

# اگر مسیر فایل استاتیک داری (مثل پوشه dist) این قسمت رو فعال کن و مسیر رو تنظیم کن
# [assets]
# directory = "./dist"
