
name = "trojan-worker-custom"
type = "javascript"
account_id = "9db606e4da7ddb225e7fc6f34cf7357e"
workers_dev = true
compatibility_date = "2022-05-03"

[build]
command = ""
upload.format = "service-worker"
upload.main = "worker.js"
